services:
  - type: web
    name: ac-selection-backend
    env: python
    region: singapore
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/main.py"
    envVars:
      - key: PORT
        value: 8000
